# Generated by Django 4.1.4 on 2022-12-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_games"),
    ]

    operations = [
        migrations.RenameField(
            model_name="games", old_name="player", new_name="playersdsds",
        ),
    ]
