# Generated by Django 4.1.4 on 2022-12-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_player_games_playersdsds"),
    ]

    operations = [
        migrations.RenameField(
            model_name="games", old_name="playersdsds", new_name="player",
        ),
    ]
