# Generated by Django 4.1.4 on 2022-12-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_games_game_alter_game_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="Last name"),
        ),
    ]
